version: '3.8'

services:
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network
    ports:
      - "8080:80"

  backend:
    build: ./backend
    networks:
      - app-network
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:latest
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog

networks:
  app-network:

volumes:
  db_data:       